name: Lint Markdown By Lint Markdown

on: [ pull_request , push]


jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action@v13.0.0
        with:
            globs: '**/*.md'